import {
  BUSINESS_NAME,
  SITE_URL,
  WHATSAPP_NUMBER,
  ADDRESS_STREET,
  ADDRESS_COMPLEMENT,
  CITY,
  STATE,
  ZIP_CODE,
  GEO_LATITUDE,
  GEO_LONGITUDE,
  INSTAGRAM_URL,
  BOOKING_URL,
  AIRBNB_URL,
  PRICE_FROM,
  PRICE_TO,
  CHECKIN_TIME,
  CHECKOUT_TIME,
} from "./constants";

export const lodgingBusinessSchema = {
  "@context": "https://schema.org",
  "@type": "LodgingBusiness",
  name: BUSINESS_NAME,
  description:
    "Apartamento de temporada a 2 minutos da praia do Ocian em Praia Grande - SP. 2 quartos, capacidade para até 5 hóspedes, ar-condicionado, Wi-Fi, Netflix e estacionamento incluso. Nota 9.3 no Booking.",
  url: SITE_URL,
  telephone: `+${WHATSAPP_NUMBER}`,
  address: {
    "@type": "PostalAddress",
    streetAddress: `${ADDRESS_STREET}, ${ADDRESS_COMPLEMENT}`,
    addressLocality: CITY,
    addressRegion: STATE,
    postalCode: ZIP_CODE,
    addressCountry: "BR",
  },
  geo: {
    "@type": "GeoCoordinates",
    latitude: GEO_LATITUDE,
    longitude: GEO_LONGITUDE,
  },
  priceRange: `${PRICE_FROM} a ${PRICE_TO} por noite`,
  numberOfRooms: 2,
  amenityFeature: [
    { "@type": "LocationFeatureSpecification", name: "Ar-condicionado", value: true },
    { "@type": "LocationFeatureSpecification", name: "Wi-Fi", value: true },
    { "@type": "LocationFeatureSpecification", name: "Netflix", value: true },
    { "@type": "LocationFeatureSpecification", name: "Estacionamento", value: true },
    { "@type": "LocationFeatureSpecification", name: "Cozinha equipada", value: true },
  ],
  checkinTime: CHECKIN_TIME,
  checkoutTime: CHECKOUT_TIME,
  petsAllowed: false,
  occupancy: {
    "@type": "QuantitativeValue",
    maxValue: 5,
  },
  aggregateRating: {
    "@type": "AggregateRating",
    ratingValue: "9.3",
    bestRating: "10",
    worstRating: "1",
    reviewCount: "45",
    ratingCount: "45",
  },
  sameAs: [INSTAGRAM_URL, BOOKING_URL, AIRBNB_URL],
};
